# Site settings
title: Mario Kozjak
description: 'A product-oriented software engineer. Passionate about the operations side of things. Spare-time musician.'
url: 'https://mario.kozjak.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mario Kozjak'
  email: kozjakm1@gmail.com
  twitter_username: mariokozjak
  facebook_username: mkozjak1
  github_username:  mkozjak
  linkedin_username: mario-kozjak-a9665b72
  lastfm_username: archman47

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
